### ISSUE TITLE
It is not possible to access from Internet Explorer browser

### ISSUE THREAD

**Issue by andreaTierra** [tierratelematics/ninjagoat#6]
Hi, I have a problem after my update of ninjagoat from 1.0.0 to 2.3.3 my application don't work in IE11.
IE11 throw an error, "Symbol" is not defined (something about javascript es6, that is not supported from IE11)
The new version of ninjagoat support IE11? If not, what will be the solution?

**Comment by lazyoft** [comment]
Hi,
Have you tried including a polyfill such as babel-polyfill inside your web page before loading the main script? This should solve the issue with ie11.

**Comment by roby-boy** [comment]
Hi,
the polyfill fixes "Symbol" undefined error. Thanks.
